name: LaTeX compilation
description: Compiles latex documents using latexmk and multiple TeXLive distributions
author: Bernhard Bermeitinger
inputs:
  texlive:
    description: TeXLive version (2016 or latest)
runs:
  using: docker
  image: docker://bermeitinger-b/action-latex:v1.0.0
  env:
    TEXLIVE: ${{ inputs.texlive }}